# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

group: edge
dist: trusty    


#<<<<<<< HEAD
#addons:
#  apt:
#    sources:
#    packages:
#      - python-sphinx
#      - python-pil
#      - python-imaging

#script: 
# - make html
#  - make html SPHINXOPTS=" -v"
#  - du -ch _build/html
#  - make clean
#  - make small SPHINXOPTS=" -v" &> errors.txt
#  - if ! grep -Fq 'build succeeded, 11 warnings' errors.txt; then cat errors.txt; exit 1; fi;
#  - du -ch _build/html
#=======

# executed. So things have to be tested oe by one.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # For cmake
      - kubuntu-backports
    packages:
      - cmake
      - python-sphinx
      - graphviz
      - texlive
      - texlive-font-utils
      - texlive-latex-extra
      - ghostscript




install:
  - pip install git+https://github.com/sphinx-doc/sphinx@stable
  - pip install sphinx-intl

#before_script:


script: 
  - mkdir build
  - cd build
  #- cmake -DLOCALE=ON -DALL_DOC=ON -DALL_LANG=ON ..
  - cmake -DHTML=ON -@OSGeoLiveDoc_DEBUG=ON ..
  - make html


#after_script: 

#after_success:
  # blank
