# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

group: edge
dist: trusty    


addons:
  apt:
    sources:
    packages:
      - python-sphinx
      - python-pil
      - python-imaging

script: 
  #- make html
  - make html SPHINXOPTS=" -v"
  - du -ch _build/html
  - make clean
  - make small SPHINXOPTS=" -v"
  - du -ch _build/html
