image: Visual Studio 2017

cache:
  - '%LOCALAPPDATA%\\pip\\Cache'

environment:
  VS_VERSION: Visual Studio 15 2017
  matrix:
  - platform: x64
    PYTHON: "C:\\Python37-x64"

matrix:
  fast_finish: true

shallow_clone: true

# https://www.appveyor.com/docs/windows-images-software/#perl
# Perl 5.20.1.2000 x86 (C:\Perl in PATH)

build_script:

  - if "%platform%" == "x64" call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # strawberry-perl-5.26.2.1-64bit-portable
  - "SET PERL_HOME=C:\\Perl"
  - "SET PATH=%PERL_HOME%\\perl\\site\\bin;%PERL_HOME%\\perl\\bin;%PERL_HOME%\\c\\bin;%PATH%"
  
  - "python -m pip install --upgrade pip"
  - pip install sphinx==1.6.5
  - pip install sphinx-intl
  - pip install sphinxjp.themes.revealjs

  - cpan App::cpanminus
  - cpanm Text::SimpleTable::AutoWidth

  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -DHTML=ON ..
  - cmake --build . --config Release

deploy: off

after_test:
  - cd %BUILD_FOLDER%
  - 7z a osgeolive-doc.zip ./build/doc/_build/html/* > nul

# Uncomment to enable debugging on the server
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  

artifacts:
  - path: osgeolive-doc.zip
    name: osgeolive-doc
    type: zip
